version: "3.8"
services:
  discord-bot:
    build: .
    container_name: "IPH-Bot"
    environment:
      DISCORD_BOT_TOKEN: "${DISCORD_BOT_TOKEN}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      MONGODB_HOST: "${MONGODB_HOST}"
    restart: "always"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.3
    container_name: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - ./data:/data/db
